//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDRFA_Client.GetPersonInfoWithPhotoEx {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GetPersonInfoWithPhotoEx.GetPersonInfoWithPhotoExSoap")]
    public interface GetPersonInfoWithPhotoExSoap {
        
        // CODEGEN: Generating message contract since element name strSecurityId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Execute", ReplyAction="*")]
        GDRFA_Client.GetPersonInfoWithPhotoEx.ExecuteResponse Execute(GDRFA_Client.GetPersonInfoWithPhotoEx.ExecuteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Execute", Namespace="http://tempuri.org/", Order=0)]
        public GDRFA_Client.GetPersonInfoWithPhotoEx.ExecuteRequestBody Body;
        
        public ExecuteRequest() {
        }
        
        public ExecuteRequest(GDRFA_Client.GetPersonInfoWithPhotoEx.ExecuteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ExecuteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strSecurityId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strRequestXml;
        
        public ExecuteRequestBody() {
        }
        
        public ExecuteRequestBody(string strSecurityId, string strRequestXml) {
            this.strSecurityId = strSecurityId;
            this.strRequestXml = strRequestXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExecuteResponse", Namespace="http://tempuri.org/", Order=0)]
        public GDRFA_Client.GetPersonInfoWithPhotoEx.ExecuteResponseBody Body;
        
        public ExecuteResponse() {
        }
        
        public ExecuteResponse(GDRFA_Client.GetPersonInfoWithPhotoEx.ExecuteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ExecuteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ExecuteResult;
        
        public ExecuteResponseBody() {
        }
        
        public ExecuteResponseBody(string ExecuteResult) {
            this.ExecuteResult = ExecuteResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GetPersonInfoWithPhotoExSoapChannel : GDRFA_Client.GetPersonInfoWithPhotoEx.GetPersonInfoWithPhotoExSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetPersonInfoWithPhotoExSoapClient : System.ServiceModel.ClientBase<GDRFA_Client.GetPersonInfoWithPhotoEx.GetPersonInfoWithPhotoExSoap>, GDRFA_Client.GetPersonInfoWithPhotoEx.GetPersonInfoWithPhotoExSoap {
        
        public GetPersonInfoWithPhotoExSoapClient() {
        }
        
        public GetPersonInfoWithPhotoExSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetPersonInfoWithPhotoExSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetPersonInfoWithPhotoExSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetPersonInfoWithPhotoExSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GDRFA_Client.GetPersonInfoWithPhotoEx.ExecuteResponse GDRFA_Client.GetPersonInfoWithPhotoEx.GetPersonInfoWithPhotoExSoap.Execute(GDRFA_Client.GetPersonInfoWithPhotoEx.ExecuteRequest request) {
            return base.Channel.Execute(request);
        }
        
        public string Execute(string strSecurityId, string strRequestXml) {
            GDRFA_Client.GetPersonInfoWithPhotoEx.ExecuteRequest inValue = new GDRFA_Client.GetPersonInfoWithPhotoEx.ExecuteRequest();
            inValue.Body = new GDRFA_Client.GetPersonInfoWithPhotoEx.ExecuteRequestBody();
            inValue.Body.strSecurityId = strSecurityId;
            inValue.Body.strRequestXml = strRequestXml;
            GDRFA_Client.GetPersonInfoWithPhotoEx.ExecuteResponse retVal = ((GDRFA_Client.GetPersonInfoWithPhotoEx.GetPersonInfoWithPhotoExSoap)(this)).Execute(inValue);
            return retVal.Body.ExecuteResult;
        }
    }
}
